version: '3'
networks:
  mynetwork:
    driver: bridge

services:
  coupon-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coupon-service
    image: coupon-service
    restart: on-failure
    ports:
      - 10555:9091
    depends_on:
      docker-mysql:
        condition: service_healthy
    environment:
      - WAIT_HOSTS=docker-mysql:3306
    volumes:
      - ./src:/app/src
      - ./target/:/app/target

  docker-mysql:
    container_name: docker-mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Mad123**
      - MYSQL_ROOT_HOST=%
    ports:
      - 6666:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 4s
      timeout: 20s
      retries: 5