version: '3'

services:
  # Eureka server
  discovery-server:
    container_name: discovery-server
    image: madchicken98/discovery-server
    ports:
      - "8761:8761"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Coupon service
  coupon-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coupon-service
    image: coupon-service
    ports:
      - "10555:9091"
    networks:
      - my-network
    depends_on:
      docker-mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    environment:
      - WAIT_HOSTS=docker-mysql:3306
    volumes:
      - ./target/:/app/target

  # Api gateway
  api-gateway:
    container_name: api-gateway
    image: madchicken98/api-gateway
    restart: on-failure
    networks:
      - my-network
    ports:
      - "8765:8765"
    depends_on:
      - discovery-server
      - coupon-service

  # Mysql db
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Mad123**
      - MYSQL_ROOT_HOST=%
    networks:
      - my-network
    ports:
      - "6666:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 4s
      timeout: 20s
      retries: 3

networks:
  my-network:
    driver: bridge