spring:
  datasource:
    url: jdbc:mysql://product-coupon-service.cxqiqdyv1xtm.us-east-1.rds.amazonaws.com:3306/coupon?createDatabaseIfNotExist=true
    username: mad
    password: Mad123**
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        globally_quoted_identifiers: true
    show-sql: true
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  data:
    rest:
      base-path: /api/v1/
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# By default AWS elastic beanstore uses this port (default)
server:
  port: 5000
