spring:
  application:
    name: COUPON-SERVICE

  # Database config
  datasource:
    url: jdbc:mysql://docker-mysql:3306/coupon?createDatabaseIfNotExist=true
    username: root
    password: Mad123**
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        globally_quot ed_identifiers: true
    show-sql: true
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  data:
    rest:
      base-path: /api/v1/
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka

server:
  port: 9091